### ISSUE TITLE
Allow for overwriting data in the datastore

### ISSUE THREAD

**Issue by c-abate** [activeshadow/minimega#84]
While debugging and working on an app I noticed I had to do the following steps each time

1. Edit the app
2. Run `phenix experiment create exp_name -t /phenix/topologies/mytopo/mytopo-topology.yaml -s /phenix/topologies/mytopo/mytopo-scenario.yaml`
3. Test
4. Make changes to the app
5. Delete the experiment, scenario, topology from the data store (i.e. `phenix config delete topology/mytopo`)
6. Run the `phenix experiment create` step 2 again
7. Repeat steps 2-6

Is there a simpler way to do that?  If not it would be nice to allow the experiment create function to overwrite what is already in the datastore.  Maybe add a flag (-overwrite) to the create function so that by default things won't be overwritten but when debugging and developing you won't need to delete things every time. Similar to how it used to work in v5

**Comment by activeshadow** [comment]
@c-abate are you talking about editing the app config in the scenario file, or editing the user app code itself?

If you're changing user app code, then you should be able to just run `phenix experiment reconfigure` after making the code changes.

If you're changing the app configuration in the scenario file, my workflow is to edit the app config in the experiment config directly via `phenix config edit experiment/<name>` and then run `phenix experiment reconfigure` after that. Once it's all ironed out you can then update the base scenario config. This works because when an experiment is created, a copy of the scenario config is copied into the experiment config, leaving the scenario config untouched.

Let me know if this doesn't make sense...

**Comment by c-abate** [comment]
@activeshadow That does make sense and seems a lot simpler than what I was going.  v6 is requiring some changes to my process. Thanks for the explanation and help.

**Comment by activeshadow** [comment]
@c-abate can I close this issue or is there still changes you think need to be made that would help the workflow?

**Comment by c-abate** [comment]
Yep it can be closed.
